- Removed redundant array filter in the message history rendering that was filtering out messages with an undefined `message.role` after it had already been filtered for undefined values earlier in the rendering.
- Removed redundant check for system messages in the chat history.
- Removed the code related to the renderers which is commented out as it is not in use.
- Added more meaningful message for when API key is not provided instead of just stating 'No api key provided', now it instructs to reload after providing API key.
- Destructured `props` object in Markdown component's `code` function to clearly outline the required props.
- Added a clear and refresh function that allows the user to clear the chat history for the Childbot.
- Created a separate Component `CodeCopyBtn` for handling the code copy to clipboard function.