- Refactored the Markdown rendering functionality to also render code blocks using SyntaxHighlighter
- Added a button to copy the code present in these blocks using the copy-to-clipboard package
- Updated the 'Clear' button functionality to remove chat history from local storage and reload the page, rather than simply clearing the state.
- Removed an unused renderer object. 
- Updated 'onKeyPress' event to prevent default and clear inputText state if 'Enter' was pressed without the 'Shift' key.
- Cleaned up some duplicate code, such as the ScrollToBottom function. Now, it uses the 'scrollTop' and 'scrollHeight' properties directly on the chat window ref. This way, the chat window always displays its last child.
- Updated the useEffect hook for localStorage to only store messages from the assistant and the user, no system messages. 
- Reorganized the code to improve readability and performance